- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageMigrationTest.php
When Package has registered migrations to publish,
resulting migration file being published without '.php'
file extension. In order to get Migration discovered and
available to run, file should be properly named in the form
of 'Y_m_d_His_migration_file_name_here.php' and should have
'.php' extension.
> Fix migration file extension when publishing from Package

- src/PackageServiceProvider.php
Because you have on line 59 variable $migrationFileName without .php and you set it:                       
```
$this->package->basePath("/../database/migrations/{$migrationFileName}.php.stub") => database_path('migrations/' . now()->format('Y_m_d_His') . '_' . Str::finish($migrationFileName, '.php')),
```
so you must check existing migrations (function migrationFileExists) with .php extension too. 
If you don't do that, condition can not work properly, e.g. current functionality return false _te_users_table.php === create_users_table_.
This pull request fix this condition and it will return true __create_users_table.php === create_users_table.php_.
> Fix migrationFileExists function

- src/Package.php
- tests/PackageServiceProviderTests/PackageCommandsTest.php
- tests/PackageServiceProviderTests/PackageMigrationsTest.php
- tests/PackageServiceProviderTests/PackageRoutesTest.php
- tests/TestClasses/FourthTestCommand.php
- tests/TestClasses/ThirdTestCommand.php
- tests/TestPackage/database/migrations/create_other_laravel_package_tools_table.php.stub
- tests/TestPackage/database/migrations/create_third_laravel_package_tools_table.php.stub
Howdy!
Awesome package as always guys. Whilst working with the package, it came to my attention that because of the level this package works at, methods like `hasCommands` and `hasMigrations` tend to have statically declared parameters rather than bringing in the values from another method or config file. As such, I thought it would be a nice touch to allow for parameters to be passed in varadically as well as in an array. 
Take the `hasCommands` method. Currently, you have to pass in parameters inside an array, like so:
```php
$this->hasCommands([Command::class, OtherCommand::class]);
```
As an alternate syntax, this PR enables you to get rid of the array declaration, like so:
```php
$this->hasCommands(Command::class, OtherCommand::class);
```
Because of how it works, it would also allow …
> Allows parameters for setup methods to be passed in as a spread array

- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageViewsTest.php
Thanks for this package, it's really nice! I'm using it and found a little issue when publishing views:
they are loaded from a directory using shortname (`$this->package->shortName()`):
```php
if ($this->package->hasViews) {
$this->loadViewsFrom($this->package->basePath('/../resources/views'), $this->package->shortName());
}
```
but they are published to a directory with the complete package name:
```php
if ($this->package->hasViews) {
$this->publishes([
$this->package->basePath('/../resources/views') => base_path("resources/views/vendor/{$this->package->name}"),
], "{$this->package->name}-views");
}
```
> Fix publish view directory

- README.md
- src/Package.php
- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageViewComponentsTest.php
- tests/TestPackage/Components/TestComponent.php
- tests/TestPackage/resources/views/component-test.blade.php
This PR adds support for [View Components](https://laravel.com/docs/8.x/packages#view-components), including publishing them as assets.  It also includes related tests and an updated readme section on using View Components.
> Add view component support

- README.md
- src/Package.php
- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageSharedDataTest.php
- tests/PackageServiceProviderTests/PackageViewComposerTest.php
- tests/TestPackage/resources/views/shared-data-2.blade.php
- tests/TestPackage/resources/views/shared-data.blade.php
This PR adds two features related to view data: view composers and sharing data globally with all views.  It adds two methods, `hasViewComposer()` and `sharesDataWithAllViews()`.
- `hasViewComposer()` registers either a [view composer](https://laravel.com/docs/8.x/views#view-composers) class or a callback.
- `sharesDataWithAllViews()` makes the specified variable name [available to all views](https://laravel.com/docs/8.x/views#sharing-data-with-all-views).
I feel that these additions will help keep Laravel package setup code clean and easy to maintain, with no real downside to having these additional methods available even if they're not used for every package.
This PR also includes relevant unit tests and updated documentation.
> View composers & shared view data

- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageCommandWithinAppTest.php
- tests/TestPackage/routes/web.php
This PR moves command registration outside the console context so that we can execute Artisan commands programmatically within the context of the application.
This change will resolve an issue I was having with the MultiTenancy package here: https://github.com/spatie/laravel-multitenancy/issues/207
I have added supporting tests to prove the functionality works as expected but I am happy to continue working on this if anyone has any feedback or change requests.
Thanks
> Execute command in context of the app

- src/PackageServiceProvider.php
Rather than the Laravel helper function 'now()' which is not normally available in Lumen, use Carbon::now() instead.
> Use Carbon::now() for Lumen compatibility.

- src/PackageServiceProvider.php
Per: #27 here and https://github.com/spatie/laravel-activitylog/pull/876
This PR will ensure migrations use expected file names once they are copied.
Before:
```
Copied File [/vendor/spatie/laravel-activitylog/migrations/AddBatchUuidColumnToActivityLogTable.php.stub] To [/database/migrations/2021_04_26_212134_AddBatchUuidColumnToActivityLogTable.php]
```
Now:
```
Copied File [/vendor/spatie/laravel-activitylog/migrations/AddBatchUuidColumnToActivityLogTable.php.stub] To [/database/migrations/2021_04_26_212425_add_batch_uuid_column_to_activity_log_table.php]
```
> Fix migration file names when copying them

- README.md
- src/PackageServiceProvider.php
I have verified currently the package doesn't allow to works with JSON translations.
The PR enables the support to JSON translation files, loading files from the package directory itself or, when available, from the `resource/vendor/package-name/` directory (needed if a customer likes to override the translations).
> Add json translations support

- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageMigrationTest.php
When registering migration files for publishing, the current implementation checks whether a migration file for a given name already exists/has been published before. If such a file exists, the package does not register that migration for publishing. 
By that we lose the ability to run `artisan vendor:publish --force` to get the latest versions of all migrations. You'd have to delete the existing migrations manually first and then run `vendor:publish` again.
With this PR, the `--force` flag will also re-publish the migrations while keeping any existing file names in place.
> Allow to re-publish migrations via artisan --force

- README.md
- src/Package.php
- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageViewsWithCustomNamespaceTest.php
This PR allows passing a custom view namespace to the `hasViews` method.
```php
$package
->name('your-package-name')
->hasViews('custom-view-namespace');
```
You can now use the views of the package like this:
```php
view('custom-view-namespace::myView');
```
> Add ability to customise view namespace

- composer.json
It looks like `Spatie\\LaravelPackageTools\\Database\\Factories\\` is not needed.
With this, I have a error when running master version of PHPStan : 
```
Fatal error: Uncaught PHPStan\BetterReflection\SourceLocator\Type\Composer\Psr\Exception\InvalidPrefixMapping: 
Provided path "Spatie\LaravelPackageTools\Database\Factories\" for prefix "/path-to-project/vendor/composer/../spatie/laravel-package-tools/database/factories" is not a directory
in phar:///path-to-project/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/Composer/Psr/Exception/InvalidPrefixMapping.php:20
```
> Remove Database\Factories from psr-4

- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageTranslationsTest.php
Switched to using `lang_path()` when accessing `lang` folder.
Checking function availability rather then Laravel version.
Ref. https://github.com/spatie/laravel-package-tools/commit/9aa990a6466115e46238ee53f02063cd3eafa735
> Use lang_path() when available

- src/PackageServiceProvider.php
PHP 8.2 deprecates `"${var}"` string interpolation pattern.
This fixes the only such occurrence in `spatie/laravel-package-tools` package.
- [PHP 8.2: `${var}` string interpolation deprecated](https://php.watch/versions/8.2/${var}-string-interpolation-deprecated)
- [RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)
> [PHP 8.2] Fix `${var}` string interpolation deprecation

- README.md
- src/Package.php
- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageMigrationTest.php
This PR adds functionality similar to what [Cashier](https://github.com/laravel/cashier-stripe) does with its migrations to have them registered and run automatically. You can call the following on the package configuration:
```php
$package
->name('my-package')
->hasMigration('create_my_package_table')
->runsMigrations();
```
To enable automatically running the migrations without needing people to publish them.
It's also possible to add a check like Cashier does:
```php
// MyPackageServiceProvider
$package
->name('my-package')
->hasMigration('create_my_package_table')
->runsMigrations(MyPackage::$runsMigrations);
```
Which allows people to disable the automatic running and publish the migrations instead and add their own additions to them if you add support for this in your package.
> Allow running of migrations

- README.md
- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageViewsWithCustomNamespaceTest.php
When your package view uses custom namespace, published view ignores the namespace and keeps using its package name for vendor-view's directory name.
For example, imagine you create a package that has some sort of image gallery. And you choose 'laravel-images' for your package view's namespace.
Now someone downloaded your package then decided to customize the views. So the person ran `php artisan vendor:publish` command to publish the views from this package.
But [according to this sources](https://github.com/spatie/laravel-package-tools/blob/11cdf05a5d747778fad2c098e86cd48d20917e37/src/PackageServiceProvider.php#L65-L69) `laravel-package-tools` uses package name for its base_path and namespace and ignoring actual view namespace which the package creator specified.
So no matter how the …
> Fix for publishing view files that has its custom namespace

- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageViewComponentsTest.php
- tests/TestPackage/Src/Components/TestComponent.php
1. Created `Alert.php` in `packagename/src/Components` directory.
2. Run vendor publish from project 
3. Receive following error
```
ERROR  Can't locate path: </mnt/Work/www/packages/packagename/src/../Components>.  
```
Current workaround is to move the Components directory out of src. `packagename/Components` this work.
Checked the source and notice the following
```php
if (count($this->package->viewComponents)) {
$this->publishes([
$this->package->basePath('/../Components') => base_path("app/View/Components/vendor/{$this->package->shortName()}"),
], "{$this->package->name}-components");
}
```
Updating the Components path in above by removing `../` should fix this issue.
> View Components publish has a bug

- src/Package.php
I have a case where I need to extend the existing `Package` class, in order to add some extra methods.
However, phpStan complaints, as the child class seems to be obligated to return the parent class, and not an extension of it 
So, changing `self` to `static`, provides the way to correct typeHint this extension
> Refactor Package methods, changing return type to `static`, in order to allow Package extension per project

- README.md
Clears up a line about the publishing of the service provider. On line 351 is say it'll use `/resources/stubs/{$nameOfYourServiceProvider}.php.stub` but on line 359 it says `/resources/stubs/{$nameOfYourServiceProvider}.php`.
I've updated line 359 to use `/resources/stubs/{$nameOfYourServiceProvider}.php.stub` which is the correct value for the file the package tools will actually use.
> Removal of publishable service provider typo

- README.md
- src/Commands/InstallCommand.php
- tests/PackageServiceProviderTests/InstallCommandTests/AssetsTest.php
This PR allows the publishing of assets from the install command, this brings the package more in line with plugins like Horizon or Nova.
> Enable publishing assets from the install command.

- src/Commands/InstallCommand.php
> test are failing because Illuminate\View\ViewServiceProvider::class, was deleted on https://github.com/laravel/laravel/pull/6159 laravel 10, not related with this PR
Apparently you have to change the provider that is used as a reference for the replace
[laravel/config/app.php#L158-L171](https://github.com/laravel/laravel/blob/5070934fc5fb8bea7a4c8eca44a6b0bd59571be7/config/app.php#L158-L171)
> Fix install command on Laravel 10.x breaking change

- src/Package.php
- src/PackageServiceProvider.php
There are some commands that should not be able to be executed from the context of web application interfaces, like InstallCommand, NetworkCommand
This PR gives us the option to register commands that will exclusively be used from the console.
Also on laravel documentation there is an example https://laravel.com/docs/10.x/packages#commands (_runningInConsole_)
**Example:**
```php
$package
->name('your-package-name')
->hasConfigFile()
// console context command
->hasConsoleCommand(ConsoleExclusiveCommand::class)
// console/web context command
->hasCommand(GlobalCommand::class)
// InstallCommand must be console context command
->hasInstallCommand(function(InstallCommand $command) {
$command
->publishMigrations();
})
```
This was broken here: #23
> Specify commands that will not be available on http calls

- README.md
- src/Commands/InstallCommand.php
- src/Package.php
- src/PackageServiceProvider.php
It should allow packages that has InertiaJS components to add them as publishable files with the install command:
```php
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Spatie\LaravelPackageTools\Package;
use MyPackage\ViewComponents\Alert;
use Spatie\LaravelPackageTools\Commands\InstallCommand;
class YourPackageServiceProvider extends PackageServiceProvider
{
public function configurePackage(Package $package): void
{
$package
->name('your-package-name')
->hasConfigFile()
->hasInertiaComponents()
->hasInstallCommand(function(InstallCommand $command) {
$command
->publishConfigFile()
->publishAssets()
->publishMigrations()
->copyAndRegisterServiceProviderInApp()
->askToStarRepoOnGitHub();
});
}
}
```
> add inertia components publish option

- src/Commands/InstallCommand.php
This PR adds a new `->publish($tag)` method on the install command that enables you to publish arbitrary tag names. For instance, we might use `->publish('nova')` to publish Nova resources from our package.
This way, we don't need to add an individual method for each possible tag name. I've also replaced all the individual `$shouldPublish***` properties with the new `$publishes` array.
Let me know what you think. Thanks!!
> Enable publishing any tag name with the install command

- src/PackageServiceProvider.php
Hey there,
I'm using your laravel settings package for my own ones. Therefore I have a settings migration file in ```database/settings```.
Now I try to publish these settings like this:
```php
->hasMigrations([
'../settings/create_mail_settings'
])
```
First publish works without a problem. But if I run it again it copies the file again because only the migrations path is checked for the file. So I changed the code to resolve the path using the given publish file.
> handle relative path in migration file exists check

- src/Commands/InstallCommand.php
checks if new skeleton is used on l11 and respects the new provides.php file
> fixed #128 - check if l11 with new skeleton is used

- src/Package.php
Fixes https://github.com/spatie/laravel-package-tools/issues/149
> Fix implicit nullable deprecation notice

- .github/workflows/run-tests.yml
- composer.json
- tests/PackageServiceProviderTests/InstallCommandTests/CopyAndRegisterServiceProviderInAppTest.php
Adding support for Laravel 11 development and testing, allowing for new features such as [registering optimization commands](https://github.com/spatie/laravel-package-tools/pull/147)
> Support Laravel 11 development

- src/Actions/GenerateMigrationName.php
- src/Package.php
- src/PackageServiceProvider.php
- src/Traits/HasAssets.php
- src/Traits/HasCommands.php
- src/Traits/HasConfigs.php
- src/Traits/HasConsoleCommands.php
- src/Traits/HasInertia.php
- src/Traits/HasInstallCommand.php
- src/Traits/HasMigrations.php
- src/Traits/HasProviders.php
- src/Traits/HasRoutes.php
- src/Traits/HasTranslations.php
- src/Traits/HasViewComponents.php
- src/Traits/HasViewComposers.php
- src/Traits/HasViewSharedData.php
- src/Traits/HasViews.php
This is a followup from pull request #145 which includes the most recent changes from master.
> General readability/extendability improvements

- src/PackageServiceProvider.php
- tests/PackageServiceProviderTests/PackageDiscoversMigrationsTest.php
- tests/PackageServiceProviderTests/PackageMigrationTest.php
- tests/TestPackage/database/migrations/2025_03_14_011123_create_custom_table.php.stub
Description
This PR addresses [this issue](https://github.com/spatie/laravel-package-tools/issues/143) where migration files were being prefixed with timestamps twice during the publishing process. The fix ensures that migration filenames are correctly formatted by stripping any redundant timestamp prefixes.
Related Issue
[#143](https://github.com/spatie/laravel-package-tools/issues/143)
> Fix: Migration Name Prefixed with by timestamp twice

- src/Concerns/PackageServiceProvider/ProcessViews.php
This PR fixes a view cache duplication issue that causes [performance overhead in normal environments](https://github.com/spatie/laravel-package-tools/discussions/170) and more seriously, [race conditions in multi-instance deployments](https://github.com/filamentphp/filament/issues/16231).
When packages register views using paths like `src/../resources/views`, Laravel generates different cache files than when using `php artisan view:cache` (which normalizes the paths). This affects all applications using packages built with `laravel-package-tools`.
Here's an example from my local testing. Two files, same contents, different last line (i.e. the view is cached twice):
File 1:
```PHP
.....
<?php endif; ?>
</div>
<?php endif; ?>
</<?php echo e($tag); ?>>
<?php /**PATH …
```
> Normalize view paths to prevent cache duplication

- src/Commands/Concerns/AskToStarRepoOnGitHub.php
The method askToStarRepoOnGitHub now accepts a second parameter to set the default answer.
> Add support for a default yes/no answer when asking to star the GitHub repo
